# Generated by Django 4.2.4 on 2023-08-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurant",
            "0003_remove_booking_comment_remove_booking_guest_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="img/menu-tems"),
        ),
    ]
