# Generated by Django 4.2.4 on 2023-08-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_menu_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="restaurant/static/img/menu-tems"
            ),
        ),
    ]
