# Generated by Django 4.2.4 on 2023-08-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_alter_menu_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_number", models.SmallIntegerField(unique=True)),
                ("capacity", models.SmallIntegerField()),
                ("is_booked", models.BooleanField(default=False)),
            ],
        ),
    ]
