# Generated by Django 4.2.4 on 2023-09-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0007_booking_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="numberOfPeople",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="phone_number",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
