# Generated by Django 4.2.4 on 2023-09-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0012_rename_config_configuration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="table",
        ),
        migrations.DeleteModel(
            name="Table",
        ),
    ]
